directories:
  output: release
  buildResources: build
appId: com.pingoai.app
productName: PingoAI
files:
  - filter:
      - loader.js
      - dist/**/*
      - main.js
      - node_modules/**/*
      - assets/**/*
      - src/**/*
      - scripts/**/*
      - native/**/*
      - '!build-obfuscate.js'
      - '!compile-bytecode.js'
      - '!dist/main-obfuscated.js'
      - '!**/*.map'
win:
  target:
    - nsis
  icon: assets/256_icon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 39.2.1
